var Config = {
  SHEET_SETTINGS: 'Settings',
  SHEET_USERS: 'Users',
  SHEET_SELECTIONS: 'Selections',
  SHEET_DAY_STATES: 'DayStates',
  SHEET_VOLUNTEERS: 'Volunteers',
  SHEET_ALLOCATIONS: 'Allocations',
  SHEET_PROGRAMME_METRICS: 'ProgrammeMetrics',
  SHEET_DAY_METRICS: 'DayMetrics',
  ENV_LIVE: 'LIVE',
  ENV_DEMO: 'DEMO',
  MAX_DISPLAY_NAME_LENGTH: 40,
  MAX_WANT_PER_DAY: 2,
  MAX_IF_AVAILABLE_PER_DAY: 4,
  TICKETS_PER_VOLUNTEER: 8,
  PROGRAMME_DATA_URL: 'https://raw.githubusercontent.com/kinczliz/sorszamvadasz/main/data/2026/programs.json',
  PROGRAMME_CACHE_TTL_SECONDS: 300,
  REGISTRATION_LOCK_TIMEOUT_MS: 5000,
  USERS_HEADERS: ['id', 'environment', 'displayName', 'displayNameKey', 'createdAt', 'lastSeen'],
  SELECTIONS_HEADERS: ['id', 'userId', 'environment', 'programmeId', 'priority', 'createdAt', 'updatedAt'],
  VOLUNTEERS_HEADERS: ['id', 'userId', 'environment', 'date', 'active', 'createdAt', 'updatedAt'],
  DAY_STATES_HEADERS: ['environment', 'date', 'state', 'updatedAt'],
  FESTIVAL_DATES_2026: ['2026-08-04', '2026-08-05', '2026-08-06', '2026-08-07', '2026-08-08'],
  PROGRAMME_DAY_DATES_2026: {
    KEDD: '2026-08-04',
    SZERDA: '2026-08-05',
    'CSÜTÖRTÖK': '2026-08-06',
    'PÉNTEK': '2026-08-07',
    SZOMBAT: '2026-08-08',
  },
  DAY_STATE_OPEN: 'OPEN',
  DAY_STATE_VALUES: ['OPEN', 'CLOSED', 'QUEUEING', 'FINISHED'],
  DAY_STATE_LOCK_TIMEOUT_MS: 5000,
  PROGRAMME_METRICS_HEADERS: ['environment', 'programmeId', 'wantCount', 'ifAvailableCount', 'metricsUpdatedAt', 'metricsVersion'],
  DAY_METRICS_HEADERS: ['environment', 'date', 'wantTotal', 'ifAvailableTotal', 'volunteerCount', 'capacity', 'chance', 'metricsUpdatedAt', 'metricsVersion'],
  CHANCE_VALUES: ['VERY_GOOD', 'GOOD', 'LOW', 'VERY_LOW', 'HOPELESS'],
  DAY_METRICS_LOCK_TIMEOUT_MS: 5000,
  METRICS_LOCK_TIMEOUT_MS: 30000,
}
